### ISSUE TITLE
Problema ao Cadastrar Titulo Recebimento

### ISSUE THREAD

**Issue by gianeFinan** [agilusinformatica/agilusfinan#14]
1 - Na tela Movimentações/Recebimento/Adcionar
2 - Preenchimento dos campos exceto: CentroCustoId e Competencia
3 - Cliquei 'Pago?'
4 - Todos os campos da linha preenchidos. Exceto campo observacao
5 - Cliquei no botão Gravar.
6 - Este erro aparece: ![image](https://cloud.githubusercontent.com/assets/15822241/11812439/15b8ea44-a323-11e5-8bea-437de1cd8162.png)

**Comment by henriquevc** [comment]
Problema resolvido
