### ISSUE TITLE
Extrato com valores divergentes na coluna de saldo

### ISSUE THREAD

**Issue by gianeFinan** [agilusinformatica/agilusfinan#15]
Extrato tirado no periodo: 01/10/2014 até 16/12/2015, gerou valores divergentes na coluna saldo conforme a imagem:
![image](https://cloud.githubusercontent.com/assets/15822241/11872165/0d8e61a2-a4bb-11e5-98c7-7563bfe2e80b.png)

**Comment by henriquevc** [comment]
Problema resolvido
