### ISSUE TITLE
Erro ao cadastrar Pessoa

### ISSUE THREAD

**Issue by gianeFinan** [agilusinformatica/agilusfinan#9]
Ao preencher os dados na tela de criação de pessoa, ocorre um erro.
Verificar o javascript, pois ao clicar no "gravar" mesmo com o erro a pessoa é salva.

**Comment by rafaellrochaa** [comment]
Como não havia nenhum tratamento de erros via javascript, a requisição ajax era disparada e a instância de pessoa era persistida, caso o objeto passado na requisição tivesse dados suficientes para criar pessoa. Então nesse caso, o objeto era persistido e o navegador disparava uma exceção desconhecida para erro no javascript. Com as novas verificações feitas no form isso não ocorreu mais em meus testes, porém não sei se é conveninente fechar essa issue. O melhor a ser feito é a equipe de desenvolvimento junto a Giane fazer mais testes, para ratificar que não há mas problemas.

**Comment by rafaellrochaa** [comment]
Problema resolvido.
